version: '3'
networks:
   mqtt-net:
       driver: bridge

services:
    portainer:
       container_name: portainer
       image: portainer/portainer-ce
       restart: always
       ports:
       - "9000:9000"
       environment:
         - TZ=Europe/London
       volumes:
          - /var/run/docker.sock:/var/run/docker.sock
          - /home/andrewcgaitskell/home_data/portainer:/data
    mariadb:
        container_name: mariadb_container
        image: mariadb_image
        build:
            context: ./mariadb
            dockerfile: Dockerfile
        ports:
        - "3306:3306"
        volumes:
            - /home/andrewcgaitskell/home_data/mariadb/:/var/lib/mysql
        networks:
            - mqtt-net
    jupyter:
       container_name: jupyter_container
       image: jupyter_image
       restart: always
       build:
            context: ./jupyter
            dockerfile: Dockerfile
       ports:
       - "8889:8888"
       volumes:
          - /home/andrewcgaitskell/home_data/jupyter:/home/jovyan/work
       networks:
            - mqtt-net
                
#    nodejs:
#        container_name: ${COMPOSE_PROJECT_NAME}_${NODEJS_SERVER_NAME}
#        image: ${NODEJS_CONTAINER_IMAGE}
#        user: ${NODEJS_USER}
#        command: ${NODEJS_COMMAND}
#        build: ./nodejs
#        ports:
#        - "4001:4001"
#        environment:
#            NODE_ENV: ${NODEJS_ENV}
#        volumes:
#            - /home/andrewcgaitskell/home_data/nodejs:/home/node/project
#        working_dir: /home/node/project
#        networks:
#            - mqtt-net

    reactjs:
        container_name: reactjs_container
        image: reactjs_image
        build:
            context: ./reactjs
            dockerfile: Dockerfile
        volumes:
           - /home/andrewcgaitskell/home_data/reactjs/src:/app/src
        ports:
           - "4000:4000"
        networks:
            - mqtt-net

    mosquitto:
        image: eclipse-mosquitto
        container_name: mosquitto
        build: ./mosquitto
        volumes:
           - /home/andrewcgaitskell/home_data/mosquitto/data:/mosquitto/data
           - /home/andrewcgaitskell/home_data/app/data/mosquitto/log:/mosquitto/log
        ports:
            - "1883:1883"
            - "8080:8080"
        networks:
            - mqtt-net

    flask:
        build: ./flask
        volumes:
           - /home/andrewcgaitskell/home_data/app/flask:/flask
        stop_signal: SIGINT
        depends_on:
           - mosquitto
        ports:
           - "5000:5000"
        networks:
            - mqtt-net

    dash:
        build: ./dash
        volumes:
           - /home/andrewcgaitskell/home_docker/dash/:/workdir
        stop_signal: SIGINT
        ports:
           - "5010:5010"
        depends_on:
           - mosquitto
        networks:
            - mqtt-net
           
#mqtt_dashboard:
#        container_name: mqtt_dashboard_container
#        image: mqtt_dashboard_image
#        build:
#            context: ./mqtt_dashboard
#            dockerfile: Dockerfile
#        depends_on:
#           - mosquitto
#        volumes:
#            - /home/andrewcgaitskell/Software/app/mqtt_dashboard/src:/app/src
#        ports:
#           - 4002:4002
